name: r_tree
version: 1.1.0
description: R-tree implementation to index and query two-dimensional data
author: Taylor Anderson <taylor.anderson@workiva.com>
homepage: https://github.com/Workiva/r_tree

environment:
  sdk: ">=2.12.3 <3.0.0"
dependencies:
 # dart2_constant: any
dev_dependencies:
  benchmark_harness: any
  build_runner: ^2.0.2
  build_test: any
  build_web_compilers: any
  coverage: any
 # dart_dev: any
  dart_style: any
  test: any

transformers:
  - $dart2js:
      sourceMaps: true
      commandLineOptions: [--trust-type-annotations]
      minify: false
